[package]
name = "deployooor_tui"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.1.4", features = ["full", "node-bindings", "signer-keystore"] }
hex = "0.4.3"
ratatui = { version = "0.27.0", features = ["all-widgets"]}
vyper-rs = "2.0.1"
thiserror = "1.0.61"
sqlx = { version = "= 0.7.0", features = ["runtime-tokio-native-tls", "sqlite"] }
tabled = "0.15.0"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
rand = "0.8.5"
tokio = {version = "1.38.0", features = ["rt-multi-thread", "macros"]}
libc = "0.2.155"
strum = "0.26.3"
color-eyre = "0.6.3"
itertools = "0.13.0"
